# Generated by Django 5.1.2 on 2024-10-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.AlterField(
            model_name='product',
            name='solana_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
