# Generated by Django 5.1.2 on 2024-10-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_organization_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_certificates/'),
        ),
    ]
